### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by DaPigGuy**

### CODE REVIEW

**Comment by DaPigGuy** [comment]
Added permission node for explosive snowballs :grinning:

**Comment by iksaku** [comment]
Omg! That's why the plugin didn't get approved xD

**Comment by DaPigGuy** [comment]
xD I was like "WTF! Why doesn't explosive snowballs work?!?" after I installed it.

**Comment by DaPigGuy** [comment]
If you want, you could give me a bit of credit. Your choice!

**Comment by iksaku** [comment]
xD Yep I will later... If I post it again xD

**Pull request merged**
